### ISSUE TITLE
Incorrect management of order book

### ISSUE THREAD

**Issue by newton108** [binance/binance-toolbox-python#16]
The sorting is not correctly implemented in line 68 and 70 of [manage_local_order_book.py](https://github.com/binance/binance-toolbox-python/blob/master/manage_local_order_book.py).
The `price` and `quantity` in line 50 are strings, and sorting based on string gives rise to bugs e.g. "9500.00" > "20000.00".

**Comment by newton108** [comment]
A quick fix: add `key = lambda e: float(e[0])` into `sorted` in those two lines.

**Comment by 2pd** [comment]
https://github.com/binance/binance-toolbox-python/pull/17  This has been fixed.
Thank you.
